# Generated by Django 2.0.6 on 2018-06-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_last_login_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.CharField(default='22', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='iphone',
            field=models.CharField(default='13412333333', max_length=13),
        ),
        migrations.AddField(
            model_name='user',
            name='job',
            field=models.CharField(default='工程师', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='xiaoxiaoabc', max_length=30),
        ),
    ]
